# System Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: system
spec:
  replicas: 3  # Added for high availability
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system-container
        image: system:1.0-SNAPSHOT
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:  # Added health check
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 20

---
# Inventory Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        image: inventory:1.0-SNAPSHOT
        ports:
        - containerPort: 9090
        env:
        - name: SYS_APP_HOSTNAME
          value: system-service
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:  # Added readiness check
          httpGet:
            path: /ready
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10

---
# System Service
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  type: NodePort
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 31000

---
# Inventory Service
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 32000    output